services:
  postgres:
    image: postgres:16-alpine
    container_name: techblog-postgres
    environment:
      POSTGRES_DB: course_blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: