server:
  port: 8080

spring:
  application:
    name: course-blog-service

  datasource:
    url: jdbc:postgresql://localhost:5432/course_blog
    username: postgres
    password: rootpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      "[hibernate.format_sql]": true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html